---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u162198909/domains/demo.lorenzogeliztienda.com/laravel
    - /bin/mkdir $DEPLOYPATH
    - /bin/rsync -a --exclude 'public' * $DEPLOYPATH
    - export DEPLOYPATH=/home/u162198909/domains/demo.lorenzogeliztienda.com/
    - /bin/cp -r ./public/ * $DEPLOYPATH
    