---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u162198909/demo.lorenzogeliztienda.com/laravel
    - /bin/cp .env.example * $DEPLOYPATH/.env
    - /bin/rsync -a --exclude 'public' * $DEPLOYPATH
    - export DEPLOYPATH=/home/u162198909/demo.lorenzogeliztienda.com
    - /bin/cp -r ./public/ * $DEPLOYPATH
    